import rrdtool
import tempfile

DAY = 86400
YEAR = 365 * DAY
fd,path = tempfile.mkstemp('.png')

rrdtool.graph('energy.1h.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-3h",
    #'--end', "-1",
    '--vertical-label', 'Wh',
    '--title', 'Energy 3h',
    '--lower-limit', '0',
    "DEF:e=energy.rrd:energy:AVERAGE",
    "DEF:e1h=energy.rrd:energy:AVERAGE:step=600",
    "LINE1:e#0000FF:energy",
    "LINE1:e1h#FF0000:energy 10m",
    "VDEF:emax=e,MAXIMUM",
    "VDEF:eavg=e,AVERAGE",
    "VDEF:emin=e,MINIMUM",
    "GPRINT:emax:Max %6.2lf Wh",
    "GPRINT:eavg:Avg %6.2lf Wh",
    "GPRINT:emin:Min %6.2lf Wh",
)

rrdtool.graph('energy.1d.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-1d",
    #'--end', "-1",
    '--vertical-label', 'Wh',
    '--title', 'Energy 1d',
    '--lower-limit', '0',
    "DEF:e=energy.rrd:energy:AVERAGE",
    "DEF:e1h=energy.rrd:energy:AVERAGE:step=3600",
    "LINE1:e#0000FF:energy",
    "LINE1:e1h#FF0000:energy 1h",
    "VDEF:emax=e,MAXIMUM",
    "VDEF:eavg=e,AVERAGE",
    "VDEF:emin=e,MINIMUM",
    "GPRINT:emax:Max %6.2lf Wh",
    "GPRINT:eavg:Avg %6.2lf Wh",
    "GPRINT:emin:Min %6.2lf Wh",
)

rrdtool.graph('energy.1w.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-1w",
    #'--end', "-1",
    '--vertical-label', 'Wh',
    '--title', 'Energy 1w',
    '--lower-limit', '0',
    "DEF:e=energy.rrd:energy:AVERAGE",
    "DEF:e1h=energy.rrd:energy:AVERAGE:step=86400",
    "LINE1:e#0000FF:energy",
    "LINE1:e1h#FF0000:energy 1d",
    "VDEF:emax=e,MAXIMUM",
    "VDEF:eavg=e,AVERAGE",
    "VDEF:emin=e,MINIMUM",
    "GPRINT:emax:Max %6.2lf Wh",
    "GPRINT:eavg:Avg %6.2lf Wh",
    "GPRINT:emin:Min %6.2lf Wh",
)

rrdtool.graph('energy.4w.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-4w",
    #'--end', "-1",
    '--vertical-label', 'Wh',
    '--title', 'Energy 4 weeks',
    '--lower-limit', '0',
    "DEF:e=energy.rrd:energy:AVERAGE",
    "DEF:e1h=energy.rrd:energy:AVERAGE:step=604800",
    "LINE1:e#0000FF:energy",
    "LINE1:e1h#FF0000:energy 1w",
    "VDEF:emax=e,MAXIMUM",
    "VDEF:eavg=e,AVERAGE",
    "VDEF:emin=e,MINIMUM",
    "GPRINT:emax:Max %6.2lf Wh",
    "GPRINT:eavg:Avg %6.2lf Wh",
    "GPRINT:emin:Min %6.2lf Wh",
)

rrdtool.graph('energy.1y.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-1y",
    #'--end', "-1",
    '--vertical-label', 'Wh',
    '--title', 'Energy 1y',
    '--lower-limit', '0',
    "DEF:e=energy.rrd:energy:AVERAGE",
    "DEF:e1h=energy.rrd:energy:AVERAGE:step=2419200",
    "LINE1:e#0000FF:energy",
    "LINE1:e1h#FF0000:energy 1w",
    "VDEF:emax=e,MAXIMUM",
    "VDEF:eavg=e,AVERAGE",
    "VDEF:emin=e,MINIMUM",
    "GPRINT:emax:Max %6.2lf Wh",
    "GPRINT:eavg:Avg %6.2lf Wh",
    "GPRINT:emin:Min %6.2lf Wh",
)

rrdtool.graph('energy.temp.1h.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-3h",
    #'--end', "-1",
    '--vertical-label', 'C',
    '--title', 'Outdoor Temperature [C] 3h',
    "DEF:temp=energy.rrd:temp:AVERAGE",
    "LINE:temp#09FF03:temp",
    "VDEF:emax=temp,MAXIMUM",
    "VDEF:eavg=temp,AVERAGE",
    "VDEF:emin=temp,MINIMUM",
    "GPRINT:emax:Max %6.2lf C",
    "GPRINT:eavg:Avg %6.2lf C",
    "GPRINT:emin:Min %6.2lf C",
)

rrdtool.graph('energy.temp.1d.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-1d",
    #'--end', "-1",
    '--vertical-label', 'C',
    '--title', 'Outdoor Temperature [C] 1d',
    "DEF:temp=energy.rrd:temp:AVERAGE",
    "LINE:temp#09FF03:temp",
    "VDEF:emax=temp,MAXIMUM",
    "VDEF:eavg=temp,AVERAGE",
    "VDEF:emin=temp,MINIMUM",
    "GPRINT:emax:Max %6.2lf C",
    "GPRINT:eavg:Avg %6.2lf C",
    "GPRINT:emin:Min %6.2lf C",
)

rrdtool.graph('energy.temp.1w.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-1w",
    #'--end', "-1",
    '--vertical-label', 'C',
    '--title', 'Outdoor Temperature [C] 1w',
    "DEF:temp=energy.rrd:temp:AVERAGE",
    "LINE:temp#09FF03:temp",
    "VDEF:emax=temp,MAXIMUM",
    "VDEF:eavg=temp,AVERAGE",
    "VDEF:emin=temp,MINIMUM",
    "GPRINT:emax:Max %6.2lf C",
    "GPRINT:eavg:Avg %6.2lf C",
    "GPRINT:emin:Min %6.2lf C",
)

rrdtool.graph('energy.temp.4w.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-4w",
    #'--end', "-1",
    '--vertical-label', 'C',
    '--title', 'Outdoor Temperature [C] 4w',
    "DEF:temp=energy.rrd:temp:AVERAGE",
    "LINE:temp#09FF03:temp",
    "VDEF:emax=temp,MAXIMUM",
    "VDEF:eavg=temp,AVERAGE",
    "VDEF:emin=temp,MINIMUM",
    "GPRINT:emax:Max %6.2lf C",
    "GPRINT:eavg:Avg %6.2lf C",
    "GPRINT:emin:Min %6.2lf C",
)

rrdtool.graph('energy.temp.1y.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-1y",
    #'--end', "-1",
    '--vertical-label', 'C',
    '--title', 'Outdoor Temperature [C] 1y',
    "DEF:temp=energy.rrd:temp:AVERAGE",
    "LINE:temp#09FF03:temp",
    "VDEF:emax=temp,MAXIMUM",
    "VDEF:eavg=temp,AVERAGE",
    "VDEF:emin=temp,MINIMUM",
    "GPRINT:emax:Max %6.2lf C",
    "GPRINT:eavg:Avg %6.2lf C",
    "GPRINT:emin:Min %6.2lf C",
)

rrdtool.graph('temp1.temp.1h.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-3h",
    #'--end', "-1",
    '--vertical-label', 'C',
    '--title', 'Indoor Temperature [C] 3h',
    "DEF:temp=temp1.rrd:temp:AVERAGE",
    "LINE:temp#09FF03:temp",
    "VDEF:emax=temp,MAXIMUM",
    "VDEF:eavg=temp,AVERAGE",
    "VDEF:emin=temp,MINIMUM",
    "GPRINT:emax:Max %6.2lf C",
    "GPRINT:eavg:Avg %6.2lf C",
    "GPRINT:emin:Min %6.2lf C",
)

rrdtool.graph('temp1.temp.1d.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-1d",
    #'--end', "-1",
    '--vertical-label', 'C',
    '--title', 'Indoor Temperature [C] 1d',
    "DEF:temp=temp1.rrd:temp:AVERAGE",
    "LINE:temp#09FF03:temp",
    "VDEF:emax=temp,MAXIMUM",
    "VDEF:eavg=temp,AVERAGE",
    "VDEF:emin=temp,MINIMUM",
    "GPRINT:emax:Max %6.2lf C",
    "GPRINT:eavg:Avg %6.2lf C",
    "GPRINT:emin:Min %6.2lf C",
)
rrdtool.graph('temp1.temp.1w.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-1w",
    #'--end', "-1",
    '--vertical-label', 'C',
    '--title', 'Indoor Temperature [C] 1w',
    "DEF:temp=temp1.rrd:temp:AVERAGE",
    "LINE:temp#09FF03:temp",
    "VDEF:emax=temp,MAXIMUM",
    "VDEF:eavg=temp,AVERAGE",
    "VDEF:emin=temp,MINIMUM",
    "GPRINT:emax:Max %6.2lf C",
    "GPRINT:eavg:Avg %6.2lf C",
    "GPRINT:emin:Min %6.2lf C",
)
rrdtool.graph('temp1.temp.4w.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-4w",
    #'--end', "-1",
    '--vertical-label', 'C',
    '--title', 'Indoor Temperature [C] 4w',
    "DEF:temp=temp1.rrd:temp:AVERAGE",
    "LINE:temp#09FF03:temp",
    "VDEF:emax=temp,MAXIMUM",
    "VDEF:eavg=temp,AVERAGE",
    "VDEF:emin=temp,MINIMUM",
    "GPRINT:emax:Max %6.2lf C",
    "GPRINT:eavg:Avg %6.2lf C",
    "GPRINT:emin:Min %6.2lf C",
)

rrdtool.graph('temp1.hum.1h.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-3h",
    #'--end', "-1",
    '--vertical-label', '%',
    '--title', 'Indoor Humidity [%] 3h',
    "DEF:temp=temp1.rrd:hum:AVERAGE",
    "LINE:temp#09FF03:temp",
    "VDEF:emax=temp,MAXIMUM",
    "VDEF:eavg=temp,AVERAGE",
    "VDEF:emin=temp,MINIMUM",
    "GPRINT:emax:Max %6.2lf Perc",
    "GPRINT:eavg:Avg %6.2lf Perc",
    "GPRINT:emin:Min %6.2lf Perc",
)
rrdtool.graph('temp1.hum.1d.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-1d",
    #'--end', "-1",
    '--vertical-label', '%',
    '--title', 'Indoor Humidity [%] 1d',
    "DEF:temp=temp1.rrd:hum:AVERAGE",
    "LINE:temp#09FF03:temp",
    "VDEF:emax=temp,MAXIMUM",
    "VDEF:eavg=temp,AVERAGE",
    "VDEF:emin=temp,MINIMUM",
    "GPRINT:emax:Max %6.2lf Perc",
    "GPRINT:eavg:Avg %6.2lf Perc",
    "GPRINT:emin:Min %6.2lf Perc",
)
rrdtool.graph('temp1.hum.1w.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-1w",
    #'--end', "-1",
    '--vertical-label', '%',
    '--title', 'Indoor Humidity [%] 1w',
    "DEF:temp=temp1.rrd:hum:AVERAGE",
    "LINE:temp#09FF03:temp",
    "VDEF:emax=temp,MAXIMUM",
    "VDEF:eavg=temp,AVERAGE",
    "VDEF:emin=temp,MINIMUM",
    "GPRINT:emax:Max %6.2lf Perc",
    "GPRINT:eavg:Avg %6.2lf Perc",
    "GPRINT:emin:Min %6.2lf Perc",
)
rrdtool.graph('temp1.hum.4w.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-4w",
    #'--end', "-1",
    '--vertical-label', '%',
    '--title', 'Indoor Humidity [%] 4w',
    "DEF:temp=temp1.rrd:hum:AVERAGE",
    "LINE:temp#09FF03:temp",
    "VDEF:emax=temp,MAXIMUM",
    "VDEF:eavg=temp,AVERAGE",
    "VDEF:emin=temp,MINIMUM",
    "GPRINT:emax:Max %6.2lf Perc",
    "GPRINT:eavg:Avg %6.2lf Perc",
    "GPRINT:emin:Min %6.2lf Perc",
)
"""Boiler Room Temperature"""
rrdtool.graph('boil.temp.1h.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-3h",
    #'--end', "-1",
    '--vertical-label', 'C',
    '--title', 'Boiler Room Temperature [C] 3h',
    "DEF:temp=boil.rrd:temp:AVERAGE",
    "LINE:temp#09FF03:temp",
    "VDEF:emax=temp,MAXIMUM",
    "VDEF:eavg=temp,AVERAGE",
    "VDEF:emin=temp,MINIMUM",
    "GPRINT:emax:Max %6.2lf C",
    "GPRINT:eavg:Avg %6.2lf C",
    "GPRINT:emin:Min %6.2lf C",
)
rrdtool.graph('boil.temp.1d.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-1d",
    #'--end', "-1",
    '--vertical-label', 'C',
    '--title', 'Boiler Room Temperature [C] 1d',
    "DEF:temp=boil.rrd:temp:AVERAGE",
    "LINE:temp#09FF03:temp",
    "VDEF:emax=temp,MAXIMUM",
    "VDEF:eavg=temp,AVERAGE",
    "VDEF:emin=temp,MINIMUM",
    "GPRINT:emax:Max %6.2lf C",
    "GPRINT:eavg:Avg %6.2lf C",
    "GPRINT:emin:Min %6.2lf C",
)
rrdtool.graph('boil.temp.1w.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-1w",
    #'--end', "-1",
    '--vertical-label', 'C',
    '--title', 'Boiler Room Temperature [C] 1w',
    "DEF:temp=boil.rrd:temp:AVERAGE",
    "LINE:temp#09FF03:temp",
    "VDEF:emax=temp,MAXIMUM",
    "VDEF:eavg=temp,AVERAGE",
    "VDEF:emin=temp,MINIMUM",
    "GPRINT:emax:Max %6.2lf C",
    "GPRINT:eavg:Avg %6.2lf C",
    "GPRINT:emin:Min %6.2lf C", 
)
rrdtool.graph('boil.temp.4w.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-4w",
    #'--end', "-1",
    '--vertical-label', 'C',
    '--title', 'Boiler Room Temperature [C] 4w',
    "DEF:temp=boil.rrd:temp:AVERAGE",
    "LINE:temp#09FF03:temp",
    "VDEF:emax=temp,MAXIMUM",
    "VDEF:eavg=temp,AVERAGE",
    "VDEF:emin=temp,MINIMUM",
    "GPRINT:emax:Max %6.2lf C",
    "GPRINT:eavg:Avg %6.2lf C",
    "GPRINT:emin:Min %6.2lf C", 
)
"""Boiler Room Humidity"""
rrdtool.graph('boil.hum.1h.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-3h",
    #'--end', "-1",
    '--vertical-label', '%',
    '--title', 'Boiler Room Humidity [%] 3h',
    "DEF:hum=boil.rrd:hum:AVERAGE",
    "LINE:hum#09FF03:hum",
    "VDEF:emax=hum,MAXIMUM",
    "VDEF:eavg=hum,AVERAGE",
    "VDEF:emin=hum,MINIMUM",
    "GPRINT:emax:Max %6.2lf Perc",
    "GPRINT:eavg:Avg %6.2lf Perc",
    "GPRINT:emin:Min %6.2lf Perc",
)
rrdtool.graph('boil.hum.1d.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-1d",
    #'--end', "-1",
    '--vertical-label', '%',
    '--title', 'Boiler Room Humidity [%] 1d',
    "DEF:hum=boil.rrd:hum:AVERAGE",
    "LINE:hum#09FF03:hum",
    "VDEF:emax=hum,MAXIMUM",
    "VDEF:eavg=hum,AVERAGE",
    "VDEF:emin=hum,MINIMUM",
    "GPRINT:emax:Max %6.2lf Perc",
    "GPRINT:eavg:Avg %6.2lf Perc",
    "GPRINT:emin:Min %6.2lf Perc",
)
rrdtool.graph('boil.hum.1w.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-1w",
    #'--end', "-1",
    '--vertical-label', '%',
    '--title', 'Boiler Room Humidity [%] 1w',
    "DEF:temp=boil.rrd:hum:AVERAGE",
    "LINE:temp#09FF03:temp",
    "VDEF:emax=temp,MAXIMUM",
    "VDEF:eavg=temp,AVERAGE",
    "VDEF:emin=temp,MINIMUM",
    "GPRINT:emax:Max %6.2lf Perc",
    "GPRINT:eavg:Avg %6.2lf Perc",
    "GPRINT:emin:Min %6.2lf Perc",
)
rrdtool.graph('boil.hum.4w.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-4w",
    #'--end', "-1",
    '--vertical-label', '%',
    '--title', 'Boiler Room Humidity [%] 4w',
    "DEF:temp=boil.rrd:hum:AVERAGE",
    "LINE:temp#09FF03:temp",
    "VDEF:emax=temp,MAXIMUM",
    "VDEF:eavg=temp,AVERAGE",
    "VDEF:emin=temp,MINIMUM",
    "GPRINT:emax:Max %6.2lf Perc",
    "GPRINT:eavg:Avg %6.2lf Perc",
    "GPRINT:emin:Min %6.2lf Perc",
)
"""Boiler Temperature"""
rrdtool.graph('boil.T0.1h.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-3h",
    #'--end', "-1",
    '--vertical-label', 'C',
    '--title', 'Boiler Temperature [C] 3h',
    "DEF:t0=boil.rrd:t0:AVERAGE",
	"DEF:t1=boil.rrd:t1:AVERAGE",
	"DEF:t2=boil.rrd:t2:AVERAGE",
	"DEF:t3=boil.rrd:t3:AVERAGE",
	"DEF:t4=boil.rrd:t4:AVERAGE",
    "LINE:t0#CC6600:OutK",
	"LINE:t1#00CC00:Heat",
	"LINE:t2#0000FF:In",
	"LINE:t3#FF00FF:OutB",
	"LINE:t4#FF0000:Out",
    "VDEF:emax=t0,MAXIMUM",
    "VDEF:eavg=t0,AVERAGE",
    "VDEF:emin=t0,MINIMUM",
    "GPRINT:emax:Max %6.2lf C",
    "GPRINT:eavg:Avg %6.2lf C",
    "GPRINT:emin:Min %6.2lf C",
)
rrdtool.graph('boil.T0.1d.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-1d",
    #'--end', "-1",
    '--vertical-label', 'C',
    '--title', 'Boiler Temperature [C] 1d',
    "DEF:t0=boil.rrd:t0:AVERAGE",
	"DEF:t1=boil.rrd:t1:AVERAGE",
	"DEF:t2=boil.rrd:t2:AVERAGE",
	"DEF:t3=boil.rrd:t3:AVERAGE",
	"DEF:t4=boil.rrd:t4:AVERAGE",
    "LINE:t0#CC6600:OutK",
	"LINE:t1#00CC00:Heat",
	"LINE:t2#0000FF:In",
	"LINE:t3#FF00FF:OutB",
	"LINE:t4#FF0000:Out",
    "VDEF:emax=t0,MAXIMUM",
    "VDEF:eavg=t0,AVERAGE",
    "VDEF:emin=t0,MINIMUM",
    "GPRINT:emax:Max %6.2lf C",
    "GPRINT:eavg:Avg %6.2lf C",
    "GPRINT:emin:Min %6.2lf C",
)
rrdtool.graph('boil.T0.1w.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-1w",
    #'--end', "-1",
    '--vertical-label', 'C',
    '--title', 'Boiler Temperature [C] 1w',
    "DEF:t0=boil.rrd:t0:AVERAGE",
	"DEF:t1=boil.rrd:t1:AVERAGE",
	"DEF:t2=boil.rrd:t2:AVERAGE",
	"DEF:t3=boil.rrd:t3:AVERAGE",
	"DEF:t4=boil.rrd:t4:AVERAGE",
    "LINE:t0#CC6600:OutK",
	"LINE:t1#00CC00:Heat",
	"LINE:t2#0000FF:In",
	"LINE:t3#FF00FF:OutB",
	"LINE:t4#FF0000:Out",
    "VDEF:emax=t0,MAXIMUM",
    "VDEF:eavg=t0,AVERAGE",
    "VDEF:emin=t0,MINIMUM",
    "GPRINT:emax:Max %6.2lf C",
    "GPRINT:eavg:Avg %6.2lf C",
    "GPRINT:emin:Min %6.2lf C",
)
rrdtool.graph('boil.T0.4w.png',
    '--imgformat', 'PNG',
    '--width', '480',
    '--height', '200',
    '--start', "end-4w",
    #'--end', "-1",
    '--vertical-label', 'C',
    '--title', 'Boiler Temperature [C] 4w',
    "DEF:t0=boil.rrd:t0:AVERAGE",
	"DEF:t1=boil.rrd:t1:AVERAGE",
	"DEF:t2=boil.rrd:t2:AVERAGE",
	"DEF:t3=boil.rrd:t3:AVERAGE",
	"DEF:t4=boil.rrd:t4:AVERAGE",
    "LINE:t0#CC6600:OutK",
	"LINE:t1#00CC00:Heat",
	"LINE:t2#0000FF:In",
	"LINE:t3#FF00FF:OutB",
	"LINE:t4#FF0000:Out",
    "VDEF:emax=t0,MAXIMUM",
    "VDEF:eavg=t0,AVERAGE",
    "VDEF:emin=t0,MINIMUM",
    "GPRINT:emax:Max %6.2lf C",
    "GPRINT:eavg:Avg %6.2lf C",
    "GPRINT:emin:Min %6.2lf C",
)